### PR TITLE
Added model loader demo

### PR DESCRIPTION
**Pull request by WEREMSOFT**
Added model loader demo.
Replaced printf with non variadic debug-print
Moved some functions to mem. Like memcpy

image
image
image
image

### CODE REVIEW

**Comment by IanSeyler** [comment]
Amazing work! I merged this manually. Not sure what the changes to helloc.c were for.

**Comment by WEREMSOFT** [comment]
Sorry. It was a mistake that i made when debugging. I thought I reverted it but seems that no. Sorry for the mess.

**Comment by IanSeyler** [comment]
No worries!

**Comment by IanSeyler** [comment]
Tested in on a physical system and it works well!

**Pull request closed without merging**
